# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com

after_success:
  - ./scripts/travis/auto_update.sh

env:
  global:
    - secure: "i6taz4QbN7Uspu5XEtTlQoZGXMNsZMVQWCafo1pTwThsx/KwJc4J/WuqzF08c++7SWPtBwQIyXdOkNDffWLZxoda5zdLFS/xiH+t1YfJEhgybH+X538QBAPKJqJqeS+3YkkK1GE2zqWX0Y+pQOQLxTXviE88Md9JFy+oeAO/IEo="

git:
  depth: 10

language: node_js

node_js:
  - "0.12"

sudo: false
